Hello-microverse
ariful04/Hello_Microvers pull request #1
Opened 2023-05-30 14:32 UTC by ariful04

2023-05-30 15:04 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)

# Hi @ariful04 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 15:04 UTC, AbelG101 commented on index.html
**THIS COMMENT IS REGARDING YOUR README FILE**
- [ ] Please make sure to remove any section descriptions from the readme as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍

   Kindly remove this and place the description of the project:
   - > Describe your project in 1 or 2 sentences.
- [ ] Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
Kindly remove this:
  - > Describe the tech stack and include only the relevant sections that apply to your project
- [ ] Please make sure to remove the section description from your "Future features" section as well.
  - > Describe between 1-3 key features of the application.
- [ ] Please make sure to remove the "Live demo" section from your readme (please take note this only applies to this PR as adding a demo link isn't required but for future projects, this section should exist).
- [ ] Once again the section description in the "Getting Started" section should also be removed so please consider removing it.
- [ ] Kindly make sure to add clear and detailed steps on how to get started with your project such as the prerequisites, setting up, etc... the default text should be removed 🎯
- [ ]  Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
Kindly remove this:
   - > Mention all of the collaborators of this project.
- [ ] Kindly as I mentioned previously all the main headlines should exist in your readme as I've noticed you've also removed the "Future Features section" Make sure to add it with at least 1 feature you'll be adding this shows future clients you've got a growth mindset by continuously adding features to your project👍.
- [ ] Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
Kindly remove this:
    - > Write a message to encourage readers to support your project
- [ ]  Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
Kindly remove this and place anyone you'd like to thank:
    - > Give credit to everyone who inspired your codebase.
- [ ] Kindly consider adding questions to the "FAQ" section so that people can easily find an answer or you can consider removing it altogether as it's an optional heading.
- [ ] I noticed you removed the License link from that section so please consider adding it again) and modify the content inside that file with your personal info, and finally add that file as a link like this: `./MIT.md` to the "License" section.

2023-05-30 15:04 UTC, AbelG101 commented on style.css
- [ ] Kindly make sure your pull Request has a summary describing introduced changes in more detail than the current one as this helps viewers get a quick understanding of the changes that were added. 😉

2023-05-30 16:35 UTC, ariful04 commented on index.html
I change my README file please recheck my pull request

2023-06-02 09:32 UTC, ariful04 commented on style.css
In this project I did:
-[ ]Add html file.
-[ ] Add css file.
-[ ]Configure Linter.
-[ ] Update Readme file as reviewer requirement.
Please recheck my code.

2023-06-02 09:51 UTC, AdnanOlarmmi requested changes
Hi @ariful04, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Fix some of the previous reviewer's changes.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 09:51 UTC, AdnanOlarmmi commented on index.html
> **THIS COMMENT IS REGARDING YOUR README FILE**
> 
> * [ ]  Please make sure to remove any section descriptions from the readme as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍
>   Kindly remove this and place the description of the project:
>   
>   * > Describe your project in 1 or 2 sentences.
> * [ ]  Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
>   Kindly remove this:
>   
>   * > Describe the tech stack and include only the relevant sections that apply to your project
> * [ ]  Please make sure to remove the section description from your "Future features" section as well.
>   
>   * > Describe between 1-3 key features of the application.
> * [ ]  Please make sure to remove the "Live demo" section from your readme (please take note this only applies to this PR as adding a demo link isn't required but for future projects, this section should exist).
> * [ ]  Once again the section description in the "Getting Started" section should also be removed so please consider removing it.
> * [ ]  Kindly make sure to add clear and detailed steps on how to get started with your project such as the prerequisites, setting up, etc... the default text should be removed 🎯
> * [ ]   Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
>   Kindly remove this:
>   
>   * > Mention all of the collaborators of this project.
> * [ ]  Kindly as I mentioned previously all the main headlines should exist in your readme as I've noticed you've also removed the "Future Features section" Make sure to add it with at least 1 feature you'll be adding this shows future clients you've got a growth mindset by continuously adding features to your project👍.
> * [ ]  Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
>   Kindly remove this:
>   
>   * > Write a message to encourage readers to support your project
> * [ ]   Kindly as I mentioned previously all section descriptions should be removed from your readme file as they are only there to guide you (the project owner) on what to place on this section and should be removed in the final version 👍.
>   Kindly remove this and place anyone you'd like to thank:
>   
>   * > Give credit to everyone who inspired your codebase.
> * [ ]  Kindly consider adding questions to the "FAQ" section so that people can easily find an answer or you can consider removing it altogether as it's an optional heading.

- [ ] Kindly fix the above suggestions by the former reviewer 😄.

2023-06-02 11:28 UTC, ariful04 commented
Hello reviewer I update  Readme file as requirement please recheck.

2023-06-02 13:04 UTC, Cabraham1 approved these changes
Hi @ariful04  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 11:06 UTC, merged